# Generated by Django 3.2 on 2023-01-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price2',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='quantity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
